repo_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo09
repo_name: CheckAAA

site_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo09
site_name: CheckAAA

use_directory_urls: False

nav:
  - Início: 'index.md'

  - Desenvolvimento Web:
    - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
    - Design: 'design/design.md'
  
  - Geração de Conteúdo:
    - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
    - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Ferramentas:
    - Ferramentas de Acessibilidade: 'tools/ferramentas.md'

theme:
  name: material
  locale: pt_BR
  titles_only: true
  logo: imagens/logo-checkaaa.png
  favicon: imagens/logo-checkaaa.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: gray
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css
