repo_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo09
repo_name: CheckAAA

site_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo09
site_name: CheckAAA

use_directory_urls: False

nav:
  - Início: 'index.md'
  
  - Design: 'design.md'

  - Desenvolvimento Web: 'desenvolvimento.md'
  
  - Geração de Conteúdo: 'conteudo.md'

  - Gestão de Projetos: 'projetos.md'

  - Ferramentas:
    - Ferramentas de Acessibilidade: 'ferramentas.md'

  - Referências: 'references.md'

theme:
  name: material
  locale: pt_BR
  titles_only: true
  logo: imagens/logo-checkaaa.png
  favicon: imagens/logo-checkaaa.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: gray
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/extra.css
